// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_t4Pk4n-Cft-WyOvnaT5HL7Yarrah1Q',
    appId: '1:316376521438:web:161929b70cd890e2b8804f',
    messagingSenderId: '316376521438',
    projectId: 'first-app-4504e',
    authDomain: 'first-app-4504e.firebaseapp.com',
    storageBucket: 'first-app-4504e.firebasestorage.app',
    measurementId: 'G-RPTLWV869Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5ts6sHFmenUtaeqeWWHZ-9UG8CEm7C4',
    appId: '1:316376521438:android:3d20592a79952d2eb8804f',
    messagingSenderId: '316376521438',
    projectId: 'first-app-4504e',
    storageBucket: 'first-app-4504e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfHFSLyRbhRGhqTrR_vqPgJqEJPTJtLQ',
    appId: '1:316376521438:ios:8fd30f0ddd329fe0b8804f',
    messagingSenderId: '316376521438',
    projectId: 'first-app-4504e',
    storageBucket: 'first-app-4504e.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfHFSLyRbhRGhqTrR_vqPgJqEJPTJtLQ',
    appId: '1:316376521438:ios:8fd30f0ddd329fe0b8804f',
    messagingSenderId: '316376521438',
    projectId: 'first-app-4504e',
    storageBucket: 'first-app-4504e.firebasestorage.app',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_t4Pk4n-Cft-WyOvnaT5HL7Yarrah1Q',
    appId: '1:316376521438:web:d3ec0ba2936a6592b8804f',
    messagingSenderId: '316376521438',
    projectId: 'first-app-4504e',
    authDomain: 'first-app-4504e.firebaseapp.com',
    storageBucket: 'first-app-4504e.firebasestorage.app',
    measurementId: 'G-QDGQEE92QL',
  );
}
